export interface FeaturedGame {
  appid: string;
  title: string;
  subtitle: string;
  description: string;
  tags: string[];
  category: 'trending' | 'rpg' | 'souls' | 'action' | 'openworld' | 'indie';
  rating: string;
  ratingPercent: number;
  approxPriceBRL: string;
  approxPriceUSD: string;
  discount?: number;
  developer: string;
  bannerImage: string;
  capsuleImage: string;
}

export const FEATURED_SPOTLIGHTS: FeaturedGame[] = [
  {
    appid: '292030',
    title: 'The Witcher 3: Wild Hunt',
    subtitle: 'RPG de Ação • CD PROJEKT RED',
    description: 'Você é Geralt de Rívia, mercenário matador de monstros. Em uma terra devastada pela guerra e infestada de feras, seu contrato atual é encontrar Ciri — a Criança da Profecia.',
    tags: ['Ação', 'Mundo Aberto', 'RPG', 'Fantasia'],
    category: 'rpg',
    rating: 'Extremamente Positivas',
    ratingPercent: 96,
    approxPriceBRL: 'R$ 129,99',
    approxPriceUSD: '$39.99',
    discount: 75,
    developer: 'CD PROJEKT RED',
    bannerImage: 'https://cdn.akamai.steamstatic.com/steam/apps/292030/capsule_616x353.jpg',
    capsuleImage: 'https://cdn.akamai.steamstatic.com/steam/apps/292030/header.jpg',
  },
  {
    appid: '1091500',
    title: 'Cyberpunk 2077',
    subtitle: 'RPG Sci-Fi • CD PROJEKT RED',
    description: 'Um RPG de ação e aventura em mundo aberto ambientado em Night City, uma megalópole obcecada por poder, glamour e modificações corporais incessantes.',
    tags: ['RPG', 'Sci-Fi', 'Mundo Aberto', 'Cyberpunk'],
    category: 'scifi' as any,
    rating: 'Muito Positivas',
    ratingPercent: 88,
    approxPriceBRL: 'R$ 199,90',
    approxPriceUSD: '$59.99',
    discount: 50,
    developer: 'CD PROJEKT RED',
    bannerImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1091500/capsule_616x353.jpg',
    capsuleImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1091500/header.jpg',
  },
  {
    appid: '1245620',
    title: 'ELDEN RING',
    subtitle: 'Souls-like • FromSoftware',
    description: 'Levante-se, Maculado, e seja guiado pela graça para portar o poder do Anel Prístino e se tornar um Lorde Prístino nas misteriosas Terras Intermédias.',
    tags: ['Souls-like', 'RPG de Ação', 'Fantasia Sombria'],
    category: 'souls',
    rating: 'Muito Positivas',
    ratingPercent: 93,
    approxPriceBRL: 'R$ 229,90',
    approxPriceUSD: '$59.99',
    developer: 'FromSoftware Inc.',
    bannerImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1245620/capsule_616x353.jpg',
    capsuleImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1245620/header.jpg',
  },
  {
    appid: '2358720',
    title: 'Black Myth: Wukong',
    subtitle: 'Ação & Mitologia • Game Science',
    description: 'Um RPG de ação baseado na rica mitologia chinesa. Parta em uma jornada como o Predestinado e descubra a verdade oculta sob o véu de uma lenda gloriosa.',
    tags: ['Ação', 'Mitologia', 'Souls-like', 'Aventura'],
    category: 'action',
    rating: 'Extremamente Positivas',
    ratingPercent: 96,
    approxPriceBRL: 'R$ 229,99',
    approxPriceUSD: '$59.99',
    developer: 'Game Science',
    bannerImage: 'https://cdn.akamai.steamstatic.com/steam/apps/2358720/capsule_616x353.jpg',
    capsuleImage: 'https://cdn.akamai.steamstatic.com/steam/apps/2358720/header.jpg',
  },
  {
    appid: '1086940',
    title: "Baldur's Gate 3",
    subtitle: 'RPG Narrativo • Larian Studios',
    description: 'Reúna seu grupo e retorne aos Reinos Esquecidos em uma história sobre companheirismo, traição, sacrifício e a sedução do poder absoluto.',
    tags: ['RPG Tático', 'D&D', 'Rico em Escolhas'],
    category: 'rpg',
    rating: 'Extremamente Positivas',
    ratingPercent: 96,
    approxPriceBRL: 'R$ 199,99',
    approxPriceUSD: '$59.99',
    developer: 'Larian Studios',
    bannerImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1086940/capsule_616x353.jpg',
    capsuleImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1086940/header.jpg',
  },
];

export const TRENDING_GAMES: FeaturedGame[] = [
  {
    appid: '1174180',
    title: 'Red Dead Redemption 2',
    subtitle: 'Rockstar Games',
    description: 'Arthur Morgan e a gangue Van der Linde são forçados a fugir pelo vasto território selvagem da América de 1899.',
    tags: ['Mundo Aberto', 'Faroeste', 'História'],
    category: 'openworld',
    rating: 'Muito Positivas',
    ratingPercent: 91,
    approxPriceBRL: 'R$ 299,90',
    approxPriceUSD: '$59.99',
    discount: 67,
    developer: 'Rockstar Games',
    bannerImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1174180/capsule_616x353.jpg',
    capsuleImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1174180/header.jpg',
  },
  {
    appid: '271590',
    title: 'Grand Theft Auto V',
    subtitle: 'Rockstar Games',
    description: 'Golpes ousados e vidas perigosas na metrópole banhada pelo sol de Los Santos e Blaine County.',
    tags: ['Mundo Aberto', 'Ação', 'Multiplayer'],
    category: 'action',
    rating: 'Muito Positivas',
    ratingPercent: 86,
    approxPriceBRL: 'R$ 82,41',
    approxPriceUSD: '$29.99',
    developer: 'Rockstar Games',
    bannerImage: 'https://cdn.akamai.steamstatic.com/steam/apps/271590/capsule_616x353.jpg',
    capsuleImage: 'https://cdn.akamai.steamstatic.com/steam/apps/271590/header.jpg',
  },
  {
    appid: '2322010',
    title: 'God of War Ragnarök',
    subtitle: 'PlayStation Publishing',
    description: 'Kratos e Atreus embarcam em uma jornada mítica pelos Nove Reinos antes do profetizado Ragnarök.',
    tags: ['Ação', 'Mitologia Nórdica', 'História'],
    category: 'action',
    rating: 'Muito Positivas',
    ratingPercent: 85,
    approxPriceBRL: 'R$ 249,90',
    approxPriceUSD: '$59.99',
    developer: 'Santa Monica Studio',
    bannerImage: 'https://cdn.akamai.steamstatic.com/steam/apps/2322010/capsule_616x353.jpg',
    capsuleImage: 'https://cdn.akamai.steamstatic.com/steam/apps/2322010/header.jpg',
  },
  {
    appid: '1145360',
    title: 'Hades II',
    subtitle: 'Supergiant Games',
    description: 'Lute além do Submundo usando feitiçaria sombria para enfrentar o Titã do Tempo nesta aclamada sequência.',
    tags: ['Roguelike', 'Ação Rápida', 'Mitologia'],
    category: 'indie',
    rating: 'Extremamente Positivas',
    ratingPercent: 94,
    approxPriceBRL: 'R$ 88,99',
    approxPriceUSD: '$29.99',
    developer: 'Supergiant Games',
    bannerImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1145360/capsule_616x353.jpg',
    capsuleImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1145360/header.jpg',
  },
  {
    appid: '553850',
    title: 'HELLDIVERS™ 2',
    subtitle: 'Arrowhead Game Studios',
    description: 'A última linha de ataque da galáxia. Aliste-se aos Helldivers e lute pela Liberdade em uma galáxia hostil.',
    tags: ['Tiro Co-op', 'Sci-Fi', 'Multiplayer'],
    category: 'action',
    rating: 'Muito Positivas',
    ratingPercent: 83,
    approxPriceBRL: 'R$ 199,50',
    approxPriceUSD: '$39.99',
    developer: 'Arrowhead Game Studios',
    bannerImage: 'https://cdn.akamai.steamstatic.com/steam/apps/553850/capsule_616x353.jpg',
    capsuleImage: 'https://cdn.akamai.steamstatic.com/steam/apps/553850/header.jpg',
  },
  {
    appid: '2246340',
    title: 'Monster Hunter Wilds',
    subtitle: 'CAPCOM Co., Ltd.',
    description: 'Cace monstros colossais em ambientes dinâmicos que mudam de tempestades a terras férteis em tempo real.',
    tags: ['Caça', 'Ação RPG', 'Co-op Online'],
    category: 'rpg',
    rating: 'Muito Positivas',
    ratingPercent: 87,
    approxPriceBRL: 'R$ 279,00',
    approxPriceUSD: '$69.99',
    developer: 'CAPCOM',
    bannerImage: 'https://cdn.akamai.steamstatic.com/steam/apps/2246340/capsule_616x353.jpg',
    capsuleImage: 'https://cdn.akamai.steamstatic.com/steam/apps/2246340/header.jpg',
  },
  {
    appid: '990080',
    title: 'Hogwarts Legacy',
    subtitle: 'Warner Bros. Games',
    description: 'Viva o inesperado no mundo bruxo do século XIX. Seu legado é o que você faz dele.',
    tags: ['Magia', 'Mundo Aberto', 'RPG'],
    category: 'openworld',
    rating: 'Muito Positivas',
    ratingPercent: 91,
    approxPriceBRL: 'R$ 249,99',
    approxPriceUSD: '$59.99',
    discount: 70,
    developer: 'Avalanche Software',
    bannerImage: 'https://cdn.akamai.steamstatic.com/steam/apps/990080/capsule_616x353.jpg',
    capsuleImage: 'https://cdn.akamai.steamstatic.com/steam/apps/990080/header.jpg',
  },
  {
    appid: '1627720',
    title: 'Lies of P',
    subtitle: 'NEOWIZ',
    description: 'Um eletrizante jogo estilo souls inspirado na fábula de Pinóquio, em uma cidade decadente da Belle Époque.',
    tags: ['Souls-like', 'Sombrio', 'Desafiador'],
    category: 'souls',
    rating: 'Muito Positivas',
    ratingPercent: 92,
    approxPriceBRL: 'R$ 249,90',
    approxPriceUSD: '$59.99',
    developer: 'Round8 Studio',
    bannerImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1627720/capsule_616x353.jpg',
    capsuleImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1627720/header.jpg',
  },
  {
    appid: '1888930',
    title: 'Palworld',
    subtitle: 'Pocketpair',
    description: 'Sobreviva e construa ao lado de criaturas misteriosas chamadas Pals em um mundo vasto e dinâmico.',
    tags: ['Sobrevivência', 'Monstros', 'Co-op'],
    category: 'openworld',
    rating: 'Muito Positivas',
    ratingPercent: 93,
    approxPriceBRL: 'R$ 88,99',
    approxPriceUSD: '$29.99',
    developer: 'Pocketpair',
    bannerImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1888930/capsule_616x353.jpg',
    capsuleImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1888930/header.jpg',
  },
  {
    appid: '730',
    title: 'Counter-Strike 2',
    subtitle: 'Valve',
    description: 'O clássico FPS competitivo da Valve, reformulado na engine Source 2 com física volumétrica e precisão de sub-tick.',
    tags: ['FPS', 'Competitivo', 'E-Sports'],
    category: 'action',
    rating: 'Muito Positivas',
    ratingPercent: 87,
    approxPriceBRL: 'Grátis',
    approxPriceUSD: 'Free',
    developer: 'Valve',
    bannerImage: 'https://cdn.akamai.steamstatic.com/steam/apps/730/capsule_616x353.jpg',
    capsuleImage: 'https://cdn.akamai.steamstatic.com/steam/apps/730/header.jpg',
  },
  {
    appid: '252490',
    title: 'Rust',
    subtitle: 'Facepunch Studios',
    description: 'O único objetivo no Rust é sobreviver. Supere a fome, a sede, feras e outros jogadores implacáveis.',
    tags: ['Sobrevivência', 'PvP', 'Construção'],
    category: 'action',
    rating: 'Muito Positivas',
    ratingPercent: 87,
    approxPriceBRL: 'R$ 103,49',
    approxPriceUSD: '$39.99',
    developer: 'Facepunch Studios',
    bannerImage: 'https://cdn.akamai.steamstatic.com/steam/apps/252490/capsule_616x353.jpg',
    capsuleImage: 'https://cdn.akamai.steamstatic.com/steam/apps/252490/header.jpg',
  },
  {
    appid: '1817070',
    title: "Marvel's Spider-Man Remastered",
    subtitle: 'PlayStation Publishing',
    description: 'Balance pelos arranha-céus de Nova York na pele de Peter Parker em uma espetacular aventura de super-herói.',
    tags: ['Super-Herói', 'Mundo Aberto', 'Ação'],
    category: 'action',
    rating: 'Extremamente Positivas',
    ratingPercent: 96,
    approxPriceBRL: 'R$ 249,90',
    approxPriceUSD: '$59.99',
    developer: 'Insomniac Games',
    bannerImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1817070/capsule_616x353.jpg',
    capsuleImage: 'https://cdn.akamai.steamstatic.com/steam/apps/1817070/header.jpg',
  },
];
